### ISSUE TITLE
[BE] DB 스키마 제작

### ISSUE THREAD

**Issue by seyoonkim48** [kdh-92/Tiggle#26]
![Untitled (5)](https://github.com/kdh-92/geojisekki/assets/83910753/5772db9f-667b-4341-8831-e3d852a01c9d)

https://dbdiagram.io/d/64927ce002bd1c4a5ecfcc5f

**Comment by kdh-92** [comment]
프로젝트를 안 넣어두셨습니다 ㅠ

**Comment by kdh-92** [comment]
**category 항목이 필요할 것 같습니다.**
- 수익 항목별, 지출 항목별, 자산 항목별 카테고리 정보 테이블이 필요합니다.
- 해당 테이블을 통해 geoji_category가 만들어지는 것이 필요할 것 같습니다.
- categories 하나로 json 형태로 데이터를 가지거나 아니면 컬럼을 나눠 배열 형태로 데이터를 가지거나 고민해봐야할 것 같습니다.

**transaction & transaction_type 필요**
- incoms, outcoms, refund 테이블을 transaction 하나로 합치는게 좋을 것 같습니다.
- transaction_type 테이블을 만들어 수입, 지출, 환불로 나누는게 좋을 것 같습니다.

**자산 항목에 따른 지갑 정보도 필요할 것 같습니다.**
- 자산 데이터가 쌓이는 테이블은 1개의 테이블로 관리가 가능하지 않을까 싶습니다.

**Comment by seyoonkim48** [comment]
프로젝트를 안넣어두었다는게 무슨 말일까요?-?

> Category 항목

유저별 카테고리를 배열로 넣을거라면 카테고리 항목이 불필요하다 생각합니다.
JSON 형태 배열을 갖는걸 생각하고 있었고요.
그렇게 했을 때 id 값을 배열에 넣는다고 해도 그 id로 빠르게 카테고리를 찾는 것도 아니고, 그저 어떠한 카테고리 값을 선택해서 가계부를 작성한다면 굳이 또 다른 테이블이 필요할까요..? 카테고리별 조회라고 해도 프론트에서 filter로 들어온 값으로 검색하면 될 거라 생각했습니다.
컬럼을 나눠 배열 형태를 가지는건 무슨 말씀이실까요? 다대다 관계에서의 조인테이블을 말씀하시는걸까요?


> transaction & transaction_type 필요

incomes, outcomes, refund를 하나의 테이블로 합치는데 transaction_type의 테이블이 또 생기고 거기서 관리를 한다는게 잘 이해되지 않습니다. ;-; 이따 만나뵙고 설명해주시면 감사드리겠습니다

> 자산 항목에 따른 지갑 정보도 필요할 것 같습니다.

제가 작성한 transaction 테이블의 accounts, money 항목에 대한 이야기가 맞을까요?
링크로 들어가시면 노트가 적혀있었는데요, accounts는 잔액을, money는 한 번의 가계부 작성 후 변화되는 돈을 의미했습니다.

**Comment by Jeong-hae-rim** [comment]
세윤님! 프로젝트에 안 넣어두셨다는 동현님의 말씀은 스크럼보드에 안 넣어두셨다는 걸 말씀하시는 거 같아요...!
어제께 저희가 스몰톡 하면서 나왔던 내용들이 좀 있어서 오늘 설명 들어보시면 좀 더 이해가 빠르실 거 같습니다.

제가 넣어두었어요!

**Comment by seyoonkim48** [comment]
아!!!!!!!!! 아 그렇네요!!!!!ㅠㅠ 감사합니다!!!!!

**Comment by seyoonkim48** [comment]
![Untitled (6)](https://github.com/kdh-92/geojisekki/assets/83910753/502bc447-9a84-4c21-bddb-5454476f8cd2)

미팅때 나눈 이야기 반영했습니다!
